[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["sparkzky", "Samuka007"]

[workspace.metadata.crane]
name = "faas-rs"

# API 模块：基于 Actix Web 提供 RESTful 接口，调用 service 模块的功能。
# 测试：编写单元测试和集成测试，确保服务的可靠性。
# 镜像管理：实现缓存逻辑，并支持镜像解包和检查功能
